services:
  frontend:
    build:
      context: ./admin
    container_name: vue-frontend
    ports:
      - "8080:80"
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: ./server
    container_name: nest-backend
    ports:
      - "8888:8888"
    networks:
      - app-network

networks:
  app-network:
