version: '3.9'

services:
  frontend:
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - "5353:80"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - mongo
      - redis
    networks:
      - app-network
    environment:
      - NODE_ENV=production

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27018:27017"  # 本地27018 映射到容器的27017
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7.0-alpine
    container_name: redis
    ports:
      - "6380:6379"  # 本地6380 映射到容器的6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
